### PR TITLE
Add AI8 to home page

### PR DESCRIPTION
**Pull request by blazgocompany**

### CODE REVIEW

**Comment by Bashamega** [comment]
Hello:)
This is not i meant by creating a tool. I meant adding the code and following the blue theme

**Comment by blazgocompany** [comment]
@Bashamega ok, but I don't know how to make it follow the blue theme. I haven't changed any of the styles, so how is it not following the blue theme?

**Comment by Bashamega** [comment]
> @Bashamega ok, but I don't know how to make it follow the blue theme. I haven't changed any of the styles, so how is it not following the blue theme?

I mean you need to make your website a part of our code base, meaning it can't be an out link. So it will be like /ai8

**Comment by blazgocompany** [comment]
Ohhhh... I can't intergrate my entire thing there so nevermind.

**Comment by blazgocompany** [comment]
One more question though, do you know anybody who may be willing to help with AI8? Maybe someone who has helped you in the past.

**Comment by blazgocompany** [comment]
One more question though, do you know anybody who may be willing to help with AI8? Maybe someone who has helped you in the past.

**Comment by Bashamega** [comment]
> One more question though, do you know anybody who may be willing to help with AI8? Maybe someone who has helped you in the past.

If it is  open source, I can help you manage it. I am already a maintainer for some projects

**Comment by blazgocompany** [comment]
Ok. It's on Github but not open-source.
________________________________

**Pull request closed without merging**
